x=msgbox("What is a Plane Without Wings", 0+64, "Jokes")
x=msgbox("A No Fly Zone", 0+64, "Jokes")
x=msgbox("What does a shoelace and Planes have in common", 0+64, "Jokes")
x=msgbox("Knots", 0+64, "Jokes")
x=msgbox("What do pilots deem funny", 0+64, "Jokes")
x=msgbox("Hi Jack", 0+64, "Jokes")
